fieldLayouts:
  6047c301-7c08-490c-b951-90e3dd4397af:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6efcc7d1-17e7-4880-9107-104c51a1a031 # Header Asset
            instructions: ''
            label: 'Header Achtergrond'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20c0032a-ff8d-4528-abd3-a36e53ef21e1 # Header Title
            instructions: ''
            label: 'Header titel'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6d2994d-170a-4259-ba5d-96dc31b313b1 # Header Description
            instructions: ''
            label: Beschrijving
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7ee97b17-343b-4bfc-b89b-6524fc2dd8af # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Header
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Page builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 2ef40c1a-fa32-405d-afc8-284aa0281b0a # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: home
hasTitleField: false
name: Home
section: 4c9b0d1e-c875-47bf-9bc4-4742167919c7 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
