childBlocks: null
field: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Page builder
fieldLayouts:
  433092b3-bfb9-483d-876f-da8795771999:
    tabs:
      -
        elements:
          -
            fieldUid: 9c73910a-04bd-4adc-94f8-1a7869ccbfbd # Cijfers
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
group: 4b2324dd-22d5-4ce9-8c64-6a342455e115 # Blocks
handle: blockFigures
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Cijfers
sortOrder: 9
topLevel: false
