childBlocks: ''
field: ed2b4993-a1f0-42e0-b7ac-721fb2c84c21 # Page builder
group: 4b2324dd-22d5-4ce9-8c64-6a342455e115 # Blocks
handle: blockCode
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Code
sortOrder: 9
topLevel: false
