contentColumnType: integer
fieldGroup: d0393e73-f781-4174-9020-2f7649b53d09
handle: blockForm
instructions: ''
name: Form
searchable: false
translationKeyFormat: null
translationMethod: none
type: Solspace\Freeform\FieldTypes\FormFieldType
