contentColumnType: text
fieldGroup: 0dae9c2c-8aab-44a0-8c73-d6f5c596c5dd # Globals
handle: contactAddress
instructions: ''
name: Adres
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
