contentColumnType: text
fieldGroup: 3fb1b8c0-2589-43d4-ae05-ed41c4110fb7 # CTA
handle: ctaLink
instructions: ''
name: Link
searchable: false
settings:
  allowCustomText: '1'
  allowTarget: '1'
  allowedLinkNames:
    1: asset
    2: category
    3: entry
    7: email
    8: tel
    9: url
  autoNoReferrer: ''
  defaultLinkName: entry
  defaultText: ''
  enableAriaLabel: ''
  enableTitle: ''
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'single:c678556d-4b65-4ad5-9b3d-5a976756af64' # Contact
                - 'single:4c9b0d1e-c875-47bf-9bc4-4742167919c7' # Home
                - 'section:c22317fe-ede2-49d6-9c1c-9dd4ba995764' # Pagina's
            -
              - allowCustomQuery
              - ''
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
translationKeyFormat: null
translationMethod: none
type: typedlinkfield\fields\LinkField
