contentColumnType: string
fieldGroup: fc99e12c-0ba6-4a24-a5da-d1bbbfe3f063 # Header
handle: headerAsset
instructions: ''
name: 'Header Asset'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
    - video
  defaultUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20' # Afbeeldingen
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20' # Afbeeldingen
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:49ded60a-198f-449b-819e-2533dde2cb20' # Afbeeldingen
    - 'volume:72299a99-247b-4138-876f-f85e0eb95839' # Videos
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
