contentColumnType: string
fieldGroup: 0dae9c2c-8aab-44a0-8c73-d6f5c596c5dd
handle: logo
instructions: ''
name: Logo
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
    - json
  defaultUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:49ded60a-198f-449b-819e-2533dde2cb20'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
