contentColumnType: string
fieldGroup: 9c7a4966-42e8-49f7-b64d-2f90f14b5dc5 # Teaser
handle: teaserImage
instructions: ''
name: 'Teaser Afbeelding'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
    - json
    - video
  defaultUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20' # Afbeeldingen
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:49ded60a-198f-449b-819e-2533dde2cb20' # Afbeeldingen
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:49ded60a-198f-449b-819e-2533dde2cb20' # Afbeeldingen
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
