enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  9c0e7bfb-10c6-4875-8c5f-03da5842320b:
    enabledByDefault: true
    hasUrls: true
    template: _resolvers/page
    uriFormat: contact
type: single
