enableVersioning: true
handle: quotes
name: Quotes
propagationMethod: all
siteSettings:
  9c0e7bfb-10c6-4875-8c5f-03da5842320b: # Craft Template
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
